"""Data models used by the Phase 1 pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class SourceRecord:
    """Origin metadata for an ingestion run."""

    id: str
    type: str
    hash: str
    text: str


@dataclass(slots=True)
class RequirementDraft:
    """A parsed requirement candidate before mechanical normalization."""

    text: str
    parent_index: int | None = None
    depends_on_indices: list[int] = field(default_factory=list)
    concern_value: int = 3
    layer: str = "Product"


@dataclass(slots=True)
class RequirementRecord:
    """A normalized requirement ready for persistence."""

    id: str
    text: str
    embedding: list[float]
    layer: str
    concern_value: int
    state: str
    version: int
    timestamp: int
    source_id: str
    parent_id: str | None = None
    depends_on_ids: list[str] = field(default_factory=list)
    supersedes_id: str | None = None


@dataclass(slots=True)
class QualityIssue:
    """A quality issue detected during refinement review."""

    code: str
    message: str
    requirement_id: str | None = None
    severity: str = "medium"
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class RefinementProposal:
    """A candidate edit generated by rules or AI assistance."""

    requirement_id: str
    original_text: str
    proposed_text: str
    concern_value: int
    issues: list[QualityIssue] = field(default_factory=list)


@dataclass(slots=True)
class AuditIssue:
    """A structural issue detected during the mechanical audit."""

    code: str
    message: str
    requirement_id: str | None = None
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class IngestResult:
    """Summary returned after an ingest run."""

    source: SourceRecord
    requirements: list[RequirementRecord]
    issues: list[AuditIssue]


@dataclass(slots=True)
class ReviewResult:
    """Summary returned after a refinement review."""

    requirement: RequirementRecord
    quality_issues: list[QualityIssue]
    proposal: RefinementProposal | None = None
